In [27]:
import numpy as np

In [32]:
grid_x, grid_y = np.meshgrid(
    np.linspace(start=0, stop=1.0, num=3),
    np.linspace(start=0, stop=1.0, num=3)
)
grid = np.concatenate((
    np.expand_dims(grid_x, axis=-1),
    np.expand_dims(grid_y, axis=-1)
), axis=-1).astype(np.float32)

grid

array([[[0. , 0. ],
        [0.5, 0. ],
        [1. , 0. ]],

       [[0. , 0.5],
        [0.5, 0.5],
        [1. , 0.5]],

       [[0. , 1. ],
        [0.5, 1. ],
        [1. , 1. ]]], dtype=float32)

In [33]:
from scipy.spatial.distance import cdist

dists = cdist(grid.reshape(-1,2), grid.reshape(-1,2))
dists

array([[0.        , 0.5       , 1.        , 0.5       , 0.70710678,
        1.11803399, 1.        , 1.11803399, 1.41421356],
       [0.5       , 0.        , 0.5       , 0.70710678, 0.5       ,
        0.70710678, 1.11803399, 1.        , 1.11803399],
       [1.        , 0.5       , 0.        , 1.11803399, 0.70710678,
        0.5       , 1.41421356, 1.11803399, 1.        ],
       [0.5       , 0.70710678, 1.11803399, 0.        , 0.5       ,
        1.        , 0.5       , 0.70710678, 1.11803399],
       [0.70710678, 0.5       , 0.70710678, 0.5       , 0.        ,
        0.5       , 0.70710678, 0.5       , 0.70710678],
       [1.11803399, 0.70710678, 0.5       , 1.        , 0.5       ,
        0.        , 1.11803399, 0.70710678, 0.5       ],
       [1.        , 1.11803399, 1.41421356, 0.5       , 0.70710678,
        1.11803399, 0.        , 0.5       , 1.        ],
       [1.11803399, 1.        , 1.11803399, 0.70710678, 0.5       ,
        0.70710678, 0.5       , 0.        , 0.5       ],


In [38]:
distance_cuttoff = 0.5
connections = np.where(np.logical_and(dists <= distance_cuttoff, dists > 0))
connections

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7,
        8, 8]),
 array([1, 3, 0, 2, 4, 1, 5, 0, 4, 6, 1, 3, 5, 7, 2, 4, 8, 3, 7, 4, 6, 8,
        5, 7]))

In [10]:
import torch

x = torch.rand(2, 2, 2, 3)
torch.mean(x, dim=(1,2,3), keepdim=True)

tensor([[[[0.5464]]],


        [[[0.5559]]]])