In [24]:
import numpy as np

In [55]:
x_bounds = np.linspace(start=0, stop=1, num=10).reshape(-1, 1).repeat(10, axis=1)
x_bounds = np.stack((x_bounds, 1.0 - x_bounds), axis=-1).min(axis=-1)

y_bounds = np.linspace(start=0, stop=1, num=10).reshape(1, -1).repeat(10, axis=0)
y_bounds = np.stack((y_bounds, 1.0 - y_bounds), axis=-1).min(axis=-1)

bounds = np.stack((x_bounds, y_bounds), axis=-1)
bounds, bounds.shape

(array([[[0.        , 0.        ],
         [0.        , 0.11111111],
         [0.        , 0.22222222],
         [0.        , 0.33333333],
         [0.        , 0.44444444],
         [0.        , 0.44444444],
         [0.        , 0.33333333],
         [0.        , 0.22222222],
         [0.        , 0.11111111],
         [0.        , 0.        ]],
 
        [[0.11111111, 0.        ],
         [0.11111111, 0.11111111],
         [0.11111111, 0.22222222],
         [0.11111111, 0.33333333],
         [0.11111111, 0.44444444],
         [0.11111111, 0.44444444],
         [0.11111111, 0.33333333],
         [0.11111111, 0.22222222],
         [0.11111111, 0.11111111],
         [0.11111111, 0.        ]],
 
        [[0.22222222, 0.        ],
         [0.22222222, 0.11111111],
         [0.22222222, 0.22222222],
         [0.22222222, 0.33333333],
         [0.22222222, 0.44444444],
         [0.22222222, 0.44444444],
         [0.22222222, 0.33333333],
         [0.22222222, 0.22222222],
         [0.22

In [ ]:
scales = np.sqrt(np.sum(np.square(actuals), axis=()))
error = forecasts - actuals

In [56]:
bounds[0, 0]

array([0., 0.])

In [57]:
bounds[1, 0]

array([0.11111111, 0.        ])

In [58]:
bounds[0, 1]

array([0.        , 0.11111111])

In [15]:
x_bounds_stacked = np.vstack([x_bounds, 1.0 - x_bounds])
x_bounds_stacked, x_bounds_stacked.shape

(array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
         0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
        [1.        , 0.88888889, 0.77777778, 0.66666667, 0.55555556,
         0.44444444, 0.33333333, 0.22222222, 0.11111111, 0.        ]]),
 (2, 10))

In [18]:
x_bounds_stacked_min = x_bounds_stacked.min(axis=0)
x_bounds_stacked_min

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.44444444, 0.33333333, 0.22222222, 0.11111111, 0.        ])

In [23]:
x_bounds_stacked_min.repeat(10, axis=0).shape

(100,)